### ISSUE TITLE
Cannot use any icons. Everything up-to-date. 

### ISSUE THREAD

**Issue by konyogony** [finnbear/yew_icons#15]
Hi! This is probably my inexperience but I have encountered an issue where I am unable to use any of the icons.

Here is my Cargo.toml file:
```toml
[package]
name = "kony-web"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21"
web-sys = "0.3"
yew-router = "0.18"
yew_icons = {version = "0.8", features = ["BOOTSTRAP_DISCORD"]}
```

My navbar.rs:
```rs
use yew_icons::{Icon, IconId};
...some code
 html! {
        <div class="w-full bg-gray-500/20 flex flex-row items-center px-[24rem] py-4 gap-1 text-xl font-semibold backdrop-blur-sm border-b border-white/5 sticky top-0">
            {title_home}
            <div class="ml-auto flex flex-row gap-8 items-center text-base font-semibold">
                {home_nav}
                {discord_nav}
                <div class="w-[1.5px] rounded-md h-5 bg-white/5" />
                <Icon icon_id={IconId::BOOTSTRAP_DISCORD}/> // <-------- Error here
            </div>
        </div>
    }
```

Error in terminal:
```
2024-08-13T11:57:07.324305Z ERROR ❌ error
error from build pipeline

Caused by:
    0: error getting cargo metadata
    1: `cargo metadata` exited with an error:     Updating crates.io index
       error: failed to select a version for `yew_icons`.
           ... required by package `kony-web v0.1.0 (/home/kony/Documents/kony_clowning_2/tailwind-yew)`
       versions that meet the requirements `^0.8` (locked to 0.8.0) are: 0.8.0
       
       the package `kony-web` depends on `yew_icons`, with features: `BOOTSTRAP_DISCORD` but `yew_icons` does not have these features.
       
       
       failed to select a version for `yew_icons` which could resolve this conflict
       
```
Notes:

- I dont have any more errors
- Downgrading yew_icons doesnt help.

I would appreciate any help. Thanks in advance and I appologise if I am making some silly mistake

**Comment by konyogony** [comment]
Found a solution! Had to change "BOOTSTRAP_DISCORD" => "BootstrapDiscord". Please consider changing all names in the gallery to match this format that actually works. I find this quite misleading and poorly executed.

**Comment by finnbear** [comment]
Thanks for reporting this. I am changing to UPPER_SNAKE_CASE on the [`constants_not_enum` branch](https://github.com/finnbear/yew_icons/tree/constants_not_enum) via #14. The GitHub workflow was misconfigured to deploy the GitHub pages gallery site from any commit, including on a pull request branch. I'm attempting to reconfigure it to only deploy the gallery from commits to `main`.
