### ISSUE TITLE
Change from Feather Icons to Lucide

### ISSUE THREAD

**Issue by tschuxxi** [finnbear/yew_icons#2]
It seems that the Feather repository is not actively maintained anymore, but there is [Lucide](https://github.com/lucide-icons/lucide) which is a fork, with an actively maintained code base. Please consider switching to Lucide.

**Comment by finnbear** [comment]
Thank you for pointing this out; I'm deprecating Feather and adding Lucide in `0.5.0`!

![image](https://user-images.githubusercontent.com/20015102/196567863-59bce7ef-ba10-402b-b33e-113b41dbf426.png)
