### ISSUE TITLE
In gallery, copy icon id to clipboard upon click

### ISSUE THREAD

**Issue by Boscop** [finnbear/yew_icons#3]
Just a suggestion:
Currently the workflow in the gallery is very cumbersome, as one has to open dev tools to inspect the icon element before being able to copy the icon id.
It would be much easier if the icon id was copied into the clipboard upon click on an icon :)

**Comment by finnbear** [comment]
> as one has to open dev tools to inspect the icon element 

Note that if you hover the icons, a tool tip was and is available. However, as clicking to copy is also a good idea, I've added it :)

**Comment by Boscop** [comment]
Thanks so much :)
(Yeah I noticed the tooltip, but a tooltip isn't copyable.)
Now the workflow is much faster :)
