### ISSUE TITLE
Cannot use any icons

### ISSUE THREAD

**Issue by dzfrias** [finnbear/yew_icons#7]
No icons work, and fail to compile. This is reproducible by copying the example. This is most likely because of the latest version of Yew.

The compiler gives this error message:
```
error[E0277]: the trait bound `Icon: yew::Component` is not satisfied
   |
21 |                     <Icon icon_id={IconId::LucideArrowUpCircle}/>
   |                      ^^^^ the trait `yew::Component` is not implemented for `Icon`
   |
   = help: the trait `yew::Component` is implemented for `ContextProvider<T>`
   = note: required for `Icon` to implement `yew::BaseComponent`
   = note: this error originates in the macro `html` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by finnbear** [comment]
> This is most likely because of the latest version of Yew.

Exactly!

I've now updated this crate, you can use version `0.7.0` with Yew `0.20`

**Comment by dzfrias** [comment]
Thank you so much! I'm looking forward to using the icons!

**Comment by dzfrias** [comment]
On trying to use the example again I'm running into the same errors. I made sure to use version `0.7` but nothing seems to have changed. @finnbear

**Comment by finnbear** [comment]
> On trying to use the example again I'm running into the same errors. I made sure to use version `0.7` but nothing seems to have changed. @finnbear

I recommend removing your `Cargo.lock` file (or at least the part referencing `yew` versions and `yew_icons` versions)

**Comment by dzfrias** [comment]
That worked for me! Sorry for the confusion!
