### ISSUE TITLE
Add Simple Icons

### ISSUE THREAD

**Issue by mondeja** [finnbear/yew_icons#8]
Hi, maintainer of [Simple Icons](https://github.com/simple-icons/simple-icons) here 👏🏼 

Have you considered to add simple-icons as part of the package? You can see all icons that the library provides at https://simpleicons.org

All icons are in a 24x24 px format using `viewBox="0 0 24 24"` (see [example here](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#5-check-the-icon)), including the brand color as part of the npm package. You may find useful [NodeJS usage](https://github.com/simple-icons/simple-icons#node-usage-) section of the docs and [metadata explanation](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#7-update-the-json-data-for-simpleiconsorg).

If you need help with the implementation I would be happy to help. Cheers!

**Comment by finnbear** [comment]
Thank you for the suggestion; I've added them via version `0.7.1` :tada: and included a small (b/c they are very detailed, so they have a large impact on loading time and binary size) sample in the gallery:
![image](https://user-images.githubusercontent.com/20015102/228656816-4da44d27-1727-4b19-ad12-9104826c00cf.png).
